### PR TITLE
fix typehint in prepare elements method

### PR DESCRIPTION
**Pull request by prolic**

### CODE REVIEW

**Comment by prolic** [comment]
Problem with ZF 2.4.0 RC5

**Comment by adamlundrigan** [comment]
It's a BC break with ZF2 ([PR #7344](https://github.com/zendframework/zf2/pull/7344)).  Changing the typehint fixes the issue for >=2.4.0 but breaks the code for <2.4.0.

**Comment by adamlundrigan** [comment]
@prolic the ZF2 PR which caused this issue was reverted

**Comment by prolic** [comment]
Thanks, but one issue is still there, see: https://github.com/adamlundrigan/LdcZendFormCTI/issues/17

the $byName property got removed in Zend\Form\Fieldset

**Pull request closed without merging**
